security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
            remember_me:
                secret:   '%env(APP_SECRET)%'
                lifetime: 604800 # 1 semaine en secondes

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } # Exemple pour les administrateurs
        - { path: ^/actualite, roles: ROLE_ACTUALITE } # Accès aux fonctionnalités Actualite
        # Ajoutez d'autres règles d'accès en fonction de vos besoins

    role_hierarchy:
        ROLE_ACTUALITE: ROLE_USER
        # Définissez la hiérarchie des rôles si nécessaire
